//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KufTheGame.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KufTheGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items/Armor/ArmorBoots.
        /// </summary>
        internal static string Armor_BootsArmorTexture {
            get {
                return ResourceManager.GetString("Armor_BootsArmorTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items/Armor/ArmorChest.
        /// </summary>
        internal static string Armor_ChestArmorTexture {
            get {
                return ResourceManager.GetString("Armor_ChestArmorTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items/Armor/ArmorGloves.
        /// </summary>
        internal static string Armor_GlovesArmorTexture {
            get {
                return ResourceManager.GetString("Armor_GlovesArmorTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items/Armor/ArmorHelmet.
        /// </summary>
        internal static string Armor_HelmetArmorTexture {
            get {
                return ResourceManager.GetString("Armor_HelmetArmorTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backgrounds/Background.
        /// </summary>
        internal static string Background_BackgroundTexture {
            get {
                return ResourceManager.GetString("Background_BackgroundTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backgrounds/SplashScreen.
        /// </summary>
        internal static string Background_SplashScreenCompany {
            get {
                return ResourceManager.GetString("Background_SplashScreenCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters/Enemies/KarateEnemySprite.
        /// </summary>
        internal static string Character_KarateEnemyTexture {
            get {
                return ResourceManager.GetString("Character_KarateEnemyTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters/Players/PlayerSprite.
        /// </summary>
        internal static string Character_PlayerTexture {
            get {
                return ResourceManager.GetString("Character_PlayerTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters/Enemies/StickEnemySprite.
        /// </summary>
        internal static string Character_StickEnemyTexture {
            get {
                return ResourceManager.GetString("Character_StickEnemyTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts/GameFont.
        /// </summary>
        internal static string Font_GameFont {
            get {
                return ResourceManager.GetString("Font_GameFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUD/Frame.
        /// </summary>
        internal static string HUD_BorderTexture {
            get {
                return ResourceManager.GetString("HUD_BorderTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUD/Clock.
        /// </summary>
        internal static string HUD_ClockTexture {
            get {
                return ResourceManager.GetString("HUD_ClockTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUD/Dragon.
        /// </summary>
        internal static string HUD_DragonTexture {
            get {
                return ResourceManager.GetString("HUD_DragonTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUD/Heart.
        /// </summary>
        internal static string HUD_HeartTexture {
            get {
                return ResourceManager.GetString("HUD_HeartTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items/Potions/HealthPotion.
        /// </summary>
        internal static string Potion_HealthPotionTexture {
            get {
                return ResourceManager.GetString("Potion_HealthPotionTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items/Potions/ImunePotion.
        /// </summary>
        internal static string Potion_ImmortalityPotionTexture {
            get {
                return ResourceManager.GetString("Potion_ImmortalityPotionTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items/Weapons/WeaponAxe.
        /// </summary>
        internal static string Weapon_AxeWeaponTexture {
            get {
                return ResourceManager.GetString("Weapon_AxeWeaponTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items/Weapons/WeaponDagger.
        /// </summary>
        internal static string Weapon_DaggerWeaponTexture {
            get {
                return ResourceManager.GetString("Weapon_DaggerWeaponTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items/Weapons/WeaponMace.
        /// </summary>
        internal static string Weapon_MaceWeaponTexture {
            get {
                return ResourceManager.GetString("Weapon_MaceWeaponTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items/Weapons/WeaponSword.
        /// </summary>
        internal static string Weapon_SwordWeaponTexture {
            get {
                return ResourceManager.GetString("Weapon_SwordWeaponTexture", resourceCulture);
            }
        }
    }
}
